name: Deploy to Azure
on:
  workflow_dispatch:
  workflow_call:
  inputs:
    environment:
      type: string
      default: 'dev'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: environment=${{ inputs.environment }}

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}