name: DevHack Workflow
on: 
  workflow_dispatch:
  issues:
    type: 
    - opened

env:
  STRING_VARIABLE: variable

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is job env.STRING_VARIABLE" 
  job2:
    name: job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is job 2"
