name: DevHack Workflow
on: workflow_dispatch
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is job 1" 
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is job 2"
